appdir: "{{ ansible_user_dir }}/spring"
branch: "main"

appuser: "{{ ansible_user_id }}"
appgroup: "{{ ansible_user_gid }}"
app_port: 8380

app_jar: ds-exc-2024-0.0.1-SNAPSHOT.jar

backend_server_url: "http://20.240.186.65:8380" # Spring Boot app's external address
app:
  VITE_BACKEND: "http://20.240.186.65:8380" # What the frontend uses to call backend
  env:
    server.port: "{{ app_port }}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:postgresql://20.240.193.149:5432/appdb
