- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    state: present

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Enable addons
  command: microk8s.enable dns storage ingress registry
