---
- name: Install and configure PostgreSQL
  hosts: dbservers
  become: yes
  become_user: root

  tasks:

    - name: Install PostgreSQL and psycopg2
      apt:
        name:
          - postgresql
          - python3-psycopg2
        state: present
        update_cache: yes
      tags: [install]

    - name: Edit postgres.conf to listen on all interfaces
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#listen_addresses ='
        line: "listen_addresses='*'"
      notify: restart postgres
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
      tags: [edit]

    - name: Edit pg_hba.conf to allow external connections
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "host all all 0.0.0.0/0 md5"
        create: yes
      notify: restart postgres
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
      tags: [edit]

    # - name: Force disconnect all users from appdb
    #   postgresql_query:
    #     db: postgres
    #     query: >
    #       SELECT pg_terminate_backend(pid)
    #       FROM pg_stat_activity
    #       WHERE datname = 'appdb' AND pid <> pg_backend_pid();
    #   become_user: postgres

    # - name: Drop appdb if it exists
    #   postgresql_db:
    #       name: appdb
    #       state: absent
    #   become_user: postgres

    - name: Create PostgreSQL user
      postgresql_user:
        name: appuser
        password: 'apppassword'
      become_user: postgres

    - name: Create PostgreSQL database
      postgresql_db:
        name: appdb
        owner: appuser
      become_user: postgres

  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted
