apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # Αν η εφαρμογή σου απαιτεί κάποιο επιπλέον μυστικό
  JWT_SECRET:        "mySuperSecretKey"
  ANOTHER_API_TOKEN: "abc123xyz"
